# Generated by Django 5.1.1 on 2024-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
