# Generated by Django 5.1.1 on 2024-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_gender_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default-user.png', null=True, upload_to='profile_photos/'),
        ),
    ]
